import Head from 'next/head'
import Image from 'next/image'
import whatsLogo from '../public/whatsAppLogo.png'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>BrotherHood Group</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <div className={styles.description}>
        <h1>BrotherHood Poker Club</h1>
        <p>Murillo chupa piroca e eu preciso do que você quer que eu coloquei na página</p>
        <a href="https://web.whatsapp.com/send?phone=5511988362072">Entre em contato conosco pelo WhatsApp</a>
        <Image src={whatsLogo} alt='Whatsapp' width={300} height={150} />
        </div>
      </main>
    </>
  )
}
